import { Tool } from "@/types/tools";
import {
  MdPalette,
  MdColorLens,
  MdAccessTime,
  MdTableChart,
  MdCode,
  MdCompareArrows,
  MdNumbers,
  MdImage,
  MdTextFields,
  MdShuffle,
  MdSort,
  MdCompare,
  MdNotes,
  MdAnalytics,
  MdPattern,
  MdSwapHoriz,
  MdFilterList,
  MdSpaceBar,
  MdLockOpen,
  MdDataArray,
  MdWeb,
  MdRotateRight,
  MdLink,
  MdDataObject,
  MdVpnKey,
  MdStyle,
  MdStorage,
  MdDescription,
  MdVisibility,
  MdCheckCircle,
  MdAutorenew,
  MdFingerprint,
  MdGeneratingTokens,
  MdPassword,
  MdQrCode,
  MdTextRotationNone,
  MdToken,
  MdGradient,
  MdCalculate,
  MdSecurity,
  MdAccountBalanceWallet,
  MdVerifiedUser,
  MdDns,
  MdKey,
  MdAttachMoney,
  MdLayers,
  MdSchedule,
  MdGavel,
  MdBatchPrediction,
  MdSearch,
  MdPreview,
  MdMemory,
  MdBugReport,
  MdError,
  MdAdminPanelSettings,
  MdLanguage,
  MdGraphicEq,
  MdCropSquare,
  MdRoundedCorner,
  MdHttp,
  MdRouter,
  MdLan,
  MdDevices,
  MdContentCut,
  MdFormatQuote,
  MdSettings,
} from "react-icons/md";

export const tools: Tool[] = [
  // Converters
  {
    id: "color-converter",
    name: "Color Converter",
    description: "Convert colors between HEX, RGB, HSL, and HSV formats",
    category: "converters",
    subcategory: "color-converters",
    path: "/tools/color-converter",
    icon: MdPalette,
  },
  {
    id: "image-color-picker",
    name: "Image Color Picker",
    description: "Pick colors from images and extract dominant color palettes",
    category: "converters",
    subcategory: "color-converters",
    path: "/tools/image-color-picker",
    icon: MdColorLens,
  },
  {
    id: "epoch-converter",
    name: "Epoch Timestamp Converter",
    description: "Convert between Unix timestamps and human-readable dates",
    category: "converters",
    subcategory: "time-converters",
    path: "/tools/epoch-converter",
    icon: MdAccessTime,
  },
  {
    id: "json-to-table",
    name: "JSON to Table/CSV",
    description: "Convert JSON arrays to tables or CSV format",
    category: "converters",
    subcategory: "data-converters",
    path: "/tools/json-to-table",
    icon: MdTableChart,
  },
  {
    id: "json-yaml",
    name: "JSON to YAML",
    description: "Convert between JSON and YAML formats",
    category: "converters",
    subcategory: "data-converters",
    path: "/tools/json-yaml",
    icon: MdCode,
  },
  {
    id: "xml-json",
    name: "XML to JSON",
    description: "Convert between XML and JSON formats",
    category: "converters",
    subcategory: "data-converters",
    path: "/tools/xml-json",
    icon: MdCompareArrows,
  },
  {
    id: "csv-json",
    name: "CSV to JSON",
    description: "Convert between CSV and JSON formats",
    category: "converters",
    subcategory: "data-converters",
    path: "/tools/csv-json",
    icon: MdTableChart,
  },
  {
    id: "json-toon",
    name: "JSON to TOON",
    description: "Convert between JSON and TOON (Token-Oriented Object Notation) for efficient LLM communication",
    category: "converters",
    subcategory: "data-converters",
    path: "/tools/json-toon",
    icon: MdCode,
  },
  {
    id: "number-base",
    name: "Number Base Converter",
    description: "Convert numbers between different bases",
    category: "converters",
    subcategory: "number-converters",
    path: "/tools/number-base",
    icon: MdNumbers,
  },
  {
    id: "image-base64",
    name: "Image to Base64",
    description: "Convert images to Base64 data URLs for embedding in HTML/CSS",
    category: "converters",
    subcategory: "data-converters",
    path: "/tools/image-base64",
    icon: MdImage,
  },
  {
    id: "markdown-html",
    name: "Markdown to HTML",
    description: "Convert between Markdown and HTML formats",
    category: "converters",
    subcategory: "data-converters",
    path: "/tools/markdown-html",
    icon: MdDescription,
  },
  {
    id: "toml-json",
    name: "TOML to JSON",
    description: "Convert between TOML and JSON formats",
    category: "converters",
    subcategory: "data-converters",
    path: "/tools/toml-json",
    icon: MdCode,
  },
  {
    id: "cron-parser",
    name: "Cron Expression Parser",
    description: "Parse cron expressions and show next execution times",
    category: "converters",
    subcategory: "time-converters",
    path: "/tools/cron-parser",
    icon: MdSchedule,
  },
  {
    id: "protobuf-json",
    name: "Protobuf to JSON",
    description: "Convert Protobuf schema definitions to JSON Schema",
    category: "converters",
    subcategory: "data-converters",
    path: "/tools/protobuf-json",
    icon: MdDataObject,
  },

  // Text
  {
    id: "case-converter",
    name: "Case Converter",
    description: "Convert text between different case formats (camelCase, snake_case, kebab-case, etc.)",
    category: "text",
    subcategory: "case-format",
    path: "/tools/case-converter",
    icon: MdTextFields,
  },
  {
    id: "escape-unescape",
    name: "Escape / Unescape",
    description: "Escape or unescape special characters in text",
    category: "text",
    subcategory: "case-format",
    path: "/tools/escape-unescape",
    icon: MdShuffle,
  },
  {
    id: "line-sorter",
    name: "Line Sorter",
    description: "Sort lines of text alphabetically with options for case sensitivity, duplicate removal, and empty line handling",
    category: "text",
    subcategory: "line-ops",
    path: "/tools/line-sorter",
    icon: MdSort,
  },
  {
    id: "list-comparer",
    name: "List Comparer",
    description: "Compare two lists and find differences",
    category: "text",
    subcategory: "comparison",
    path: "/tools/list-comparer",
    icon: MdCompare,
  },
  {
    id: "lorem-ipsum",
    name: "Lorem Ipsum Generator",
    description: "Generate Lorem Ipsum placeholder text",
    category: "text",
    subcategory: "text-generators",
    path: "/tools/lorem-ipsum",
    icon: MdNotes,
  },
  {
    id: "text-comparer",
    name: "Text Comparer",
    description: "Compare two texts and highlight differences",
    category: "text",
    subcategory: "comparison",
    path: "/tools/text-comparer",
    icon: MdCompare,
  },
  {
    id: "text-analyzer",
    name: "Text Analyzer",
    description: "Comprehensive text analysis with word count, character count, reading time, and advanced statistics",
    category: "text",
    subcategory: "analysis",
    path: "/tools/text-analyzer",
    icon: MdAnalytics,
  },
  {
    id: "regex-tester",
    name: "Regular Expression Tester",
    description: "Test and debug regular expressions with live matching",
    category: "text",
    subcategory: "analysis",
    path: "/tools/regex-tester",
    icon: MdPattern,
  },
  {
    id: "reverse-string",
    name: "Reverse String",
    description: "Reverse text character by character",
    category: "text",
    subcategory: "case-format",
    path: "/tools/reverse-string",
    icon: MdSwapHoriz,
  },
  {
    id: "remove-duplicates",
    name: "Remove Duplicates",
    description: "Remove duplicate lines from text while preserving the first occurrence",
    category: "text",
    subcategory: "line-ops",
    path: "/tools/remove-duplicates",
    icon: MdFilterList,
  },
  {
    id: "whitespace-remover",
    name: "Whitespace Remover",
    description: "Remove or normalize whitespace in text with multiple options",
    category: "text",
    subcategory: "case-format",
    path: "/tools/whitespace-remover",
    icon: MdSpaceBar,
  },
  {
    id: "slug-generator",
    name: "Slug Generator",
    description: "Generate URL-friendly slugs from text",
    category: "text",
    subcategory: "case-format",
    path: "/tools/slug-generator",
    icon: MdLink,
  },
  {
    id: "string-truncator",
    name: "String Truncator",
    description: "Truncate strings with various options for ellipsis position and word boundaries",
    category: "text",
    subcategory: "case-format",
    path: "/tools/string-truncator",
    icon: MdContentCut,
  },
  {
    id: "word-frequency",
    name: "Word Frequency Counter",
    description: "Count word frequencies in text with filtering options",
    category: "text",
    subcategory: "analysis",
    path: "/tools/word-frequency",
    icon: MdAnalytics,
  },
  {
    id: "ascii-art",
    name: "Text to ASCII Art",
    description: "Convert text to ASCII art with multiple font styles",
    category: "text",
    subcategory: "text-generators",
    path: "/tools/ascii-art",
    icon: MdTextFields,
  },

  // Encoders / Decoders
  {
    id: "base64-text",
    name: "Base64 Text",
    description: "Encode and decode Base64 text",
    category: "encoders-decoders",
    subcategory: "text-encoders",
    path: "/tools/base64-text",
    icon: MdLockOpen,
  },
  {
    id: "binary-text",
    name: "Binary Encoder/Decoder",
    description: "Encode text to binary or decode binary back to text",
    category: "encoders-decoders",
    subcategory: "text-encoders",
    path: "/tools/binary-text",
    icon: MdDataArray,
  },
  {
    id: "html-encoder",
    name: "HTML Encoder/Decoder",
    description: "Encode and decode HTML entities",
    category: "encoders-decoders",
    subcategory: "text-encoders",
    path: "/tools/html-encoder",
    icon: MdWeb,
  },
  {
    id: "rot13",
    name: "ROT13 Cipher",
    description: "Encode and decode text using the ROT13 Caesar cipher",
    category: "encoders-decoders",
    subcategory: "crypto-encoders",
    path: "/tools/rot13",
    icon: MdRotateRight,
  },
  {
    id: "url-encoder",
    name: "URL Encoder/Decoder",
    description: "Encode and decode URL components",
    category: "encoders-decoders",
    subcategory: "text-encoders",
    path: "/tools/url-encoder",
    icon: MdLink,
  },
  {
    id: "hex-text",
    name: "Hex Encoder/Decoder",
    description: "Convert text to hexadecimal and vice versa",
    category: "encoders-decoders",
    subcategory: "text-encoders",
    path: "/tools/hex-text",
    icon: MdCode,
  },
  {
    id: "jwt-decoder",
    name: "JWT Decoder",
    description: "Decode and inspect JSON Web Tokens (JWT) to view header, payload, and signature",
    category: "encoders-decoders",
    subcategory: "crypto-encoders",
    path: "/tools/jwt-decoder",
    icon: MdVpnKey,
  },
  {
    id: "punycode",
    name: "Punycode Encoder/Decoder",
    description: "Encode and decode Punycode for internationalized domain names",
    category: "encoders-decoders",
    subcategory: "text-encoders",
    path: "/tools/punycode",
    icon: MdLanguage,
  },
  {
    id: "unicode-escape",
    name: "Unicode Escape Encoder",
    description: "Convert text to and from Unicode escape sequences",
    category: "encoders-decoders",
    subcategory: "text-encoders",
    path: "/tools/unicode-escape",
    icon: MdCode,
  },
  {
    id: "morse-code",
    name: "Morse Code Translator",
    description: "Translate text to and from Morse code with audio playback",
    category: "encoders-decoders",
    subcategory: "crypto-encoders",
    path: "/tools/morse-code",
    icon: MdGraphicEq,
  },

  // Formatters
  {
    id: "css-formatter",
    name: "CSS Formatter/Minifier",
    description: "Format or minify CSS stylesheets",
    category: "formatters",
    subcategory: "code-formatters",
    path: "/tools/css-formatter",
    icon: MdStyle,
  },
  {
    id: "sql-formatter",
    name: "SQL Formatter",
    description: "Format and beautify SQL queries with proper indentation",
    category: "formatters",
    subcategory: "code-formatters",
    path: "/tools/sql-formatter",
    icon: MdStorage,
  },
  {
    id: "xml-formatter",
    name: "XML Formatter",
    description: "Format and validate XML with proper indentation",
    category: "formatters",
    subcategory: "code-formatters",
    path: "/tools/xml-formatter",
    icon: MdDescription,
  },
  {
    id: "svg-viewer",
    name: "SVG Viewer",
    description: "View and preview SVG code with syntax highlighting",
    category: "formatters",
    subcategory: "code-formatters",
    path: "/tools/svg-viewer",
    icon: MdVisibility,
  },
  {
    id: "yaml-validator",
    name: "YAML Validator",
    description: "Validate YAML syntax and view parsed result as JSON",
    category: "formatters",
    subcategory: "data-formatters",
    path: "/tools/yaml-validator",
    icon: MdCheckCircle,
  },
  {
    id: "json-formatter",
    name: "JSON Formatter",
    description: "Format, minify, and validate JSON data",
    category: "formatters",
    subcategory: "code-formatters",
    path: "/tools/json-formatter",
    icon: MdDataObject,
  },
  {
    id: "js-formatter",
    name: "JavaScript/TypeScript Formatter",
    description: "Format and beautify JavaScript and TypeScript code",
    category: "formatters",
    subcategory: "code-formatters",
    path: "/tools/js-formatter",
    icon: MdCode,
  },
  {
    id: "html-formatter",
    name: "HTML Formatter",
    description: "Format and beautify HTML code with proper indentation",
    category: "formatters",
    subcategory: "code-formatters",
    path: "/tools/html-formatter",
    icon: MdWeb,
  },
  {
    id: "graphql-formatter",
    name: "GraphQL Formatter",
    description: "Format and beautify GraphQL queries and schemas",
    category: "formatters",
    subcategory: "code-formatters",
    path: "/tools/graphql-formatter",
    icon: MdCode,
  },
  {
    id: "markdown-preview",
    name: "Markdown Preview",
    description: "Live preview of Markdown content with GitHub Flavored Markdown support",
    category: "formatters",
    subcategory: "data-formatters",
    path: "/tools/markdown-preview",
    icon: MdPreview,
  },

  // Generators
  {
    id: "color-palette-generator",
    name: "Color Palette Generator",
    description: "Generate beautiful color palettes with various schemes",
    category: "generators",
    subcategory: "color-generators",
    path: "/tools/color-palette-generator",
    icon: MdAutorenew,
  },
  {
    id: "hash-generator",
    name: "Hash / Checksum",
    description: "Generate various hash checksums",
    category: "generators",
    subcategory: "crypto-generators",
    path: "/tools/hash-generator",
    icon: MdFingerprint,
  },
  {
    id: "nanoid-generator",
    name: "Nanoid Generator",
    description: "Generate compact, URL-safe unique IDs",
    category: "generators",
    subcategory: "id-generators",
    path: "/tools/nanoid-generator",
    icon: MdGeneratingTokens,
  },
  {
    id: "password-generator",
    name: "Password Generator",
    description: "Generate secure random passwords",
    category: "generators",
    subcategory: "crypto-generators",
    path: "/tools/password-generator",
    icon: MdPassword,
  },
  {
    id: "qr-code-generator",
    name: "QR Code Generator",
    description: "Generate QR codes from text or URLs",
    category: "generators",
    subcategory: "color-generators",
    path: "/tools/qr-code-generator",
    icon: MdQrCode,
  },
  {
    id: "random-string-generator",
    name: "Random String Generator",
    description: "Generate random strings with various character types",
    category: "generators",
    subcategory: "text-generators",
    path: "/tools/random-string-generator",
    icon: MdTextRotationNone,
  },
  {
    id: "uuid-generator",
    name: "UUID Generator",
    description: "Generate UUIDs (v1, v4, v5)",
    category: "generators",
    subcategory: "id-generators",
    path: "/tools/uuid-generator",
    icon: MdToken,
  },
  {
    id: "gradient-generator",
    name: "Gradient Generator",
    description: "Create beautiful CSS gradients with multiple color stops",
    category: "generators",
    subcategory: "color-generators",
    path: "/tools/gradient-generator",
    icon: MdGradient,
  },
  {
    id: "cron-generator",
    name: "Cron Expression Generator",
    description: "Visual cron expression builder with presets and human-readable descriptions",
    category: "generators",
    subcategory: "text-generators",
    path: "/tools/cron-generator",
    icon: MdSchedule,
  },
  {
    id: "gitignore-generator",
    name: ".gitignore Generator",
    description: "Generate .gitignore files for various languages and frameworks",
    category: "generators",
    subcategory: "text-generators",
    path: "/tools/gitignore-generator",
    icon: MdDescription,
  },
  {
    id: "readme-generator",
    name: "README Generator",
    description: "Generate README.md templates with customizable sections",
    category: "generators",
    subcategory: "text-generators",
    path: "/tools/readme-generator",
    icon: MdDescription,
  },
  {
    id: "license-generator",
    name: "License Generator",
    description: "Generate common open source license files",
    category: "generators",
    subcategory: "text-generators",
    path: "/tools/license-generator",
    icon: MdGavel,
  },
  {
    id: "regex-generator",
    name: "Regex Generator",
    description: "Generate regular expressions from common patterns with explanations",
    category: "generators",
    subcategory: "text-generators",
    path: "/tools/regex-generator",
    icon: MdPattern,
  },
  {
    id: "box-shadow-generator",
    name: "Box Shadow Generator",
    description: "Visual CSS box-shadow generator with multiple shadows support",
    category: "generators",
    subcategory: "color-generators",
    path: "/tools/box-shadow-generator",
    icon: MdCropSquare,
  },
  {
    id: "border-radius-generator",
    name: "Border Radius Generator",
    description: "Visual CSS border-radius generator with individual corner control",
    category: "generators",
    subcategory: "color-generators",
    path: "/tools/border-radius-generator",
    icon: MdRoundedCorner,
  },
  {
    id: "favicon-generator",
    name: "Favicon Generator",
    description: "Generate simple text or emoji favicons with customizable colors",
    category: "generators",
    subcategory: "color-generators",
    path: "/tools/favicon-generator",
    icon: MdImage,
  },

  // Web3
  {
    id: "function-selector",
    name: "Function Selector",
    description: "Calculate Solidity function selectors",
    category: "web3",
    subcategory: "contracts",
    path: "/tools/function-selector",
    icon: MdCode,
  },
  {
    id: "keccak-hash",
    name: "Keccak-256 Hash",
    description: "Calculate Keccak-256 hash",
    category: "web3",
    subcategory: "encoding",
    path: "/tools/keccak-hash",
    icon: MdFingerprint,
  },
  {
    id: "eth-unit-converter",
    name: "ETH Unit Converter",
    description: "Convert between Wei, Gwei, and ETH",
    category: "web3",
    subcategory: "token-decimals",
    path: "/tools/eth-unit-converter",
    icon: MdSwapHoriz,
  },
  {
    id: "abi-encoder",
    name: "ABI Encoder/Decoder",
    description: "Encode and decode Ethereum ABI data",
    category: "web3",
    subcategory: "contracts",
    path: "/tools/abi-encoder",
    icon: MdDataObject,
  },
  {
    id: "address-checksum",
    name: "Address Checksum",
    description: "Convert Ethereum addresses to checksum format",
    category: "web3",
    subcategory: "address-keys",
    path: "/tools/address-checksum",
    icon: MdCheckCircle,
  },
  {
    id: "event-topic",
    name: "Event Topic Calculator",
    description: "Calculate event signature hashes for Solidity events",
    category: "web3",
    subcategory: "contracts",
    path: "/tools/event-topic",
    icon: MdCalculate,
  },
  {
    id: "signature-verifier",
    name: "Signature Verifier",
    description: "Verify Ethereum signatures (ECDSA)",
    category: "web3",
    subcategory: "contracts",
    path: "/tools/signature-verifier",
    icon: MdVerifiedUser,
  },
  {
    id: "ens-resolver",
    name: "ENS Name Resolver",
    description: "Resolve ENS names to Ethereum addresses",
    category: "web3",
    subcategory: "address-keys",
    path: "/tools/ens-resolver",
    icon: MdDns,
  },
  {
    id: "transaction-decoder",
    name: "Transaction Decoder",
    description: "Decode raw Ethereum transaction data",
    category: "web3",
    subcategory: "transaction-gas",
    path: "/tools/transaction-decoder",
    icon: MdCode,
  },
  {
    id: "private-key-to-address",
    name: "Private Key to Address",
    description: "Convert private key to Ethereum address",
    category: "web3",
    subcategory: "address-keys",
    path: "/tools/private-key-to-address",
    icon: MdKey,
  },
  {
    id: "mnemonic-generator",
    name: "Mnemonic Generator/Validator",
    description: "Generate and validate BIP39 mnemonic phrases",
    category: "web3",
    subcategory: "crypto-generators",
    path: "/tools/mnemonic-generator",
    icon: MdGeneratingTokens,
  },
  {
    id: "gas-estimator",
    name: "Gas Price Estimator",
    description: "Estimate Ethereum transaction costs in ETH and USD",
    category: "web3",
    subcategory: "transaction-gas",
    path: "/tools/gas-estimator",
    icon: MdAttachMoney,
  },
  {
    id: "token-decimals-converter",
    name: "Token Decimals Converter",
    description: "Convert between human-readable amounts and raw token amounts",
    category: "web3",
    subcategory: "token-decimals",
    path: "/tools/token-decimals-converter",
    icon: MdToken,
  },
  {
    id: "method-id-finder",
    name: "Smart Contract Method ID Finder",
    description: "Look up smart contract method signatures by their 4-byte method ID",
    category: "web3",
    subcategory: "contracts",
    path: "/tools/method-id-finder",
    icon: MdSearch,
  },
  {
    id: "contract-storage-slot",
    name: "Contract Storage Slot Calculator",
    description: "Calculate storage slots for mappings and arrays in Solidity smart contracts",
    category: "web3",
    subcategory: "contracts",
    path: "/tools/contract-storage-slot",
    icon: MdStorage,
  },
  {
    id: "eip712-hasher",
    name: "EIP-712 Message Hasher",
    description: "Calculate EIP-712 hashes for typed structured data signing",
    category: "web3",
    subcategory: "encoding",
    path: "/tools/eip712-hasher",
    icon: MdFingerprint,
  },
  {
    id: "ecdsa-signature",
    name: "ECDSA Signature Parser",
    description: "Parse ECDSA signatures into r, s, v components",
    category: "web3",
    subcategory: "encoding",
    path: "/tools/ecdsa-signature",
    icon: MdSecurity,
  },
  // DeFi & Protocol Tools
  {
    id: "uniswap-price-calculator",
    name: "Uniswap Price Calculator",
    description: "Calculate token prices, slippage, and impermanent loss for Uniswap pools",
    category: "web3",
    subcategory: "defi",
    path: "/tools/uniswap-price-calculator",
    icon: MdCalculate,
  },
  {
    id: "token-launch-calculator",
    name: "Token Launch Calculator",
    description: "Calculate tokenomics for liquidity pool creation and token launches",
    category: "web3",
    subcategory: "defi",
    path: "/tools/token-launch-calculator",
    icon: MdToken,
  },
  {
    id: "timelock-transaction-builder",
    name: "Timelock Transaction Builder",
    description: "Build timelock governance transactions with calldata and ETA",
    category: "web3",
    subcategory: "governance",
    path: "/tools/timelock-transaction-builder",
    icon: MdSchedule,
  },
  {
    id: "multi-chain-address-deriver",
    name: "Multi-Chain Address Deriver",
    description: "Derive addresses from private keys or mnemonics across multiple EVM chains",
    category: "web3",
    subcategory: "address-keys",
    path: "/tools/multi-chain-address-deriver",
    icon: MdLayers,
  },
  // Smart Contract Development Tools
  {
    id: "safe-batch-builder",
    name: "Safe Batch Transaction Builder",
    description: "Build batch transactions for Gnosis Safe multi-sig wallets",
    category: "web3",
    subcategory: "governance",
    path: "/tools/safe-batch-builder",
    icon: MdBatchPrediction,
  },
  {
    id: "proxy-implementation-checker",
    name: "Proxy Implementation Checker",
    description: "Check proxy contract implementations and admin addresses",
    category: "web3",
    subcategory: "contracts",
    path: "/tools/proxy-implementation-checker",
    icon: MdSearch,
  },
  {
    id: "create2-address-predictor",
    name: "CREATE2 Address Predictor",
    description: "Predict contract addresses using CREATE2 and find vanity addresses",
    category: "web3",
    subcategory: "contracts",
    path: "/tools/create2-address-predictor",
    icon: MdPreview,
  },
  {
    id: "contract-size-calculator",
    name: "Contract Size Calculator",
    description: "Calculate contract bytecode size and check against 24KB limit",
    category: "web3",
    subcategory: "contracts",
    path: "/tools/contract-size-calculator",
    icon: MdMemory,
  },
  // Testing & Debugging Tools
  {
    id: "foundry-cheatcode-generator",
    name: "Foundry Cheatcode Generator",
    description: "Generate Foundry test cheatcodes (vm.prank, vm.deal, vm.warp, etc.)",
    category: "web3",
    subcategory: "testing",
    path: "/tools/foundry-cheatcode-generator",
    icon: MdCode,
  },
  {
    id: "block-timestamp-converter",
    name: "Block Number ⇔ Timestamp",
    description: "Convert between block numbers and timestamps for different chains",
    category: "web3",
    subcategory: "testing",
    path: "/tools/block-timestamp-converter",
    icon: MdAccessTime,
  },
  {
    id: "revert-reason-decoder",
    name: "Revert Reason Decoder",
    description: "Decode revert reasons from failed transactions",
    category: "web3",
    subcategory: "testing",
    path: "/tools/revert-reason-decoder",
    icon: MdError,
  },
  {
    id: "trace-visualizer",
    name: "Transaction Trace Visualizer",
    description: "Visualize transaction execution traces with call hierarchy",
    category: "web3",
    subcategory: "testing",
    path: "/tools/trace-visualizer",
    icon: MdVisibility,
  },
  // Token & NFT Tools
  {
    id: "erc20-permit-generator",
    name: "ERC20 Permit Generator",
    description: "Generate EIP-2612 permit signatures for gasless approvals",
    category: "web3",
    subcategory: "token-nft",
    path: "/tools/erc20-permit-generator",
    icon: MdToken,
  },
  {
    id: "nft-metadata-validator",
    name: "NFT Metadata Validator",
    description: "Validate NFT metadata against OpenSea and ERC standards",
    category: "web3",
    subcategory: "token-nft",
    path: "/tools/nft-metadata-validator",
    icon: MdCheckCircle,
  },
  {
    id: "token-uri-generator",
    name: "Token URI Generator",
    description: "Generate token URIs for IPFS, Arweave, and data URIs",
    category: "web3",
    subcategory: "token-nft",
    path: "/tools/token-uri-generator",
    icon: MdLink,
  },
  // Security & Analysis Tools
  {
    id: "bytecode-differ",
    name: "Bytecode Differ",
    description: "Compare contract bytecodes to verify implementations",
    category: "web3",
    subcategory: "security",
    path: "/tools/bytecode-differ",
    icon: MdCompare,
  },
  {
    id: "access-control-visualizer",
    name: "Access Control Visualizer",
    description: "Visualize contract access control patterns and roles",
    category: "web3",
    subcategory: "security",
    path: "/tools/access-control-visualizer",
    icon: MdAdminPanelSettings,
  },
  {
    id: "delegatecall-analyzer",
    name: "Delegatecall Storage Analyzer",
    description: "Analyze storage layout compatibility for delegatecall and proxies",
    category: "web3",
    subcategory: "security",
    path: "/tools/delegatecall-analyzer",
    icon: MdStorage,
  },

  // Utilities
  {
    id: "json-path",
    name: "JSON Path Finder",
    description: "Find and extract values from JSON using JSONPath expressions",
    category: "utilities",
    subcategory: "data-tools",
    path: "/tools/json-path",
    icon: MdSearch,
  },
  {
    id: "diff-viewer",
    name: "Diff Viewer",
    description: "Compare two texts side by side with line-by-line or word-by-word diff",
    category: "utilities",
    subcategory: "comparison",
    path: "/tools/diff-viewer",
    icon: MdCompare,
  },
  {
    id: "chmod-calculator",
    name: "Chmod Calculator",
    description: "Convert between numeric and symbolic Unix file permissions",
    category: "utilities",
    subcategory: "unix-tools",
    path: "/tools/chmod-calculator",
    icon: MdSecurity,
  },
  {
    id: "http-status",
    name: "HTTP Status Code Reference",
    description: "Searchable reference for HTTP status codes with descriptions",
    category: "utilities",
    subcategory: "reference",
    path: "/tools/http-status",
    icon: MdHttp,
  },
  {
    id: "ascii-table",
    name: "ASCII Table Reference",
    description: "Searchable ASCII character table with decimal, hex, and binary values",
    category: "utilities",
    subcategory: "reference",
    path: "/tools/ascii-table",
    icon: MdTableChart,
  },
  {
    id: "ip-calculator",
    name: "IP Address Calculator",
    description: "Calculate subnet information from IP/CIDR notation",
    category: "utilities",
    subcategory: "network-tools",
    path: "/tools/ip-calculator",
    icon: MdRouter,
  },
  {
    id: "cidr-calculator",
    name: "CIDR Calculator",
    description: "Convert between CIDR notation and IP ranges, split subnets",
    category: "utilities",
    subcategory: "network-tools",
    path: "/tools/cidr-calculator",
    icon: MdLan,
  },
  {
    id: "user-agent-parser",
    name: "User Agent Parser",
    description: "Parse User-Agent strings to extract browser, OS, and device information",
    category: "utilities",
    subcategory: "web-tools",
    path: "/tools/user-agent-parser",
    icon: MdDevices,
  },
  {
    id: "crontab-guru",
    name: "Crontab Guru",
    description: "Explain cron expressions in human-readable form with next execution times",
    category: "utilities",
    subcategory: "unix-tools",
    path: "/tools/crontab-guru",
    icon: MdSchedule,
  },
];

export function getToolsByCategory(category: string) {
  return tools.filter((tool) => tool.category === category);
}

export function getToolById(id: string) {
  return tools.find((tool) => tool.id === id);
}
